# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

variables:
  branch: 8.*.x
  version: v8

trigger:
  branches:
    include:
    - $(branch)

resources:
  repositories:
  - repository: self
    type: git
    ref: $(branch)

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run lint
    npm run test:libs
    npm run build:libs
    npm run cover:libs
    npm run doc:libs
  displayName: 'npm install, lint, test and build'

- task: PublishTestResults@2
  displayName: Publish test results
  inputs:
    testResultsFiles: dist/$(version)/tests/dynamic-forms-libs.junit.xml

- task: PublishCodeCoverageResults@1
  displayName: Publish code coverage
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: dist/$(version)/tests/cobertura-coverage.xml

- script: |
    npm run build:demo -- --base-href=/$(version)/dev/
  displayName: npm build demo (dev)

- task: CopyFiles@2
  inputs:
    contents: 'dist/$(version)/**'
    targetFolder: $(Build.ArtifactStagingDirectory)/dev

- script: |
    npm run build:demo:prod -- --base-href=/$(version)/
  displayName: npm build demo (prod)

- task: CopyFiles@2
  inputs:
    contents: 'dist/$(version)/**'
    targetFolder: $(Build.ArtifactStagingDirectory)/prod

- task: PublishBuildArtifacts@1
  displayName: Publish Artifact (dev)
  inputs:
    PathtoPublish: $(Build.ArtifactStagingDirectory)
    ArtifactName: dynamic-forms-$(version)
