export interface DynamicFormFieldUpdateDebounce {
  time: number;
}

export type DynamicFormFieldUpdate = 'change' | 'debounce' | 'blur' | DynamicFormFieldUpdateDebounce;

export interface DynamicFormFieldOptions {
  autoGeneratedId?: boolean;
  update?: DynamicFormFieldUpdate;
}

export const dynamicFormFieldDefaultDebounceTime = 300;

